//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hour
    {
        public decimal EMP_NUM { get; set; }
        public decimal ATTRACT_NO { get; set; }
        public decimal HOURS_PER_ATTRACT { get; set; }
        public decimal HOUR_RATE { get; set; }
        public System.DateTime DATE_WORKED { get; set; }
    
        public virtual attraction attraction { get; set; }
        public virtual employee employee { get; set; }
    }
}
