//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_line
    {
        public decimal TRANSACTION_NO { get; set; }
        public decimal LINE_NO { get; set; }
        public decimal TICKET_NO { get; set; }
        public decimal LINE_QTY { get; set; }
        public decimal LINE_PRICE { get; set; }
    
        public virtual sale sale { get; set; }
        public virtual ticket ticket { get; set; }
    }
}
