//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class themepark
    {
        public themepark()
        {
            this.attractions = new HashSet<attraction>();
            this.employees = new HashSet<employee>();
            this.sales = new HashSet<sale>();
            this.tickets = new HashSet<ticket>();
        }
    
        public string PARK_CODE { get; set; }
        public string PARK_NAME { get; set; }
        public string PARK_CITY { get; set; }
        public string PARK_COUNTRY { get; set; }
    
        public virtual ICollection<attraction> attractions { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<sale> sales { get; set; }
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
