//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public ticket()
        {
            this.sales_line = new HashSet<sales_line>();
        }
    
        public decimal TICKET_NO { get; set; }
        public decimal TICKET_PRICE { get; set; }
        public string TICKET_TYPE { get; set; }
        public string PARK_CODE { get; set; }
    
        public virtual ICollection<sales_line> sales_line { get; set; }
        public virtual themepark themepark { get; set; }
    }
}
