//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatch_Processing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lmc1Entities : DbContext
    {
        public lmc1Entities()
            : base("name=lmc1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<copy1_4> copy1_4 { get; set; }
        public DbSet<copy2_3> copy2_3 { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<despatch_instruction_cover_dic_> despatch_instruction_cover_dic_ { get; set; }
        public DbSet<despatch_instruction_detail_did_> despatch_instruction_detail_did_ { get; set; }
        public DbSet<diset> disets { get; set; }
        public DbSet<invoiceset> invoicesets { get; set; }
        public DbSet<invoicing_section> invoicing_section { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<purchase_order> purchase_order { get; set; }
        public DbSet<sales_office> sales_office { get; set; }
        public DbSet<shipman> shipmen { get; set; }
        public DbSet<spare_parts_store> spare_parts_store { get; set; }
        public DbSet<spares_despatch_department> spares_despatch_department { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<stockrecord> stockrecords { get; set; }
        public DbSet<supply> supplies { get; set; }
        public DbSet<user> users { get; set; }
    }
}
