//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatch_Processing
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        public string LMSerialNumber { get; set; }
        public string StockID { get; set; }
        public int CustomerUserID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderSerial { get; set; }
        public string DeliveryAddress { get; set; }
        public string ProductNo { get; set; }
        public int OrderQty { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
        public int OrderNo { get; set; }
    }
}
