//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class attraction
    {
        public attraction()
        {
            this.hours = new HashSet<hour>();
        }
    
        public decimal ATTRACT_NO { get; set; }
        public string ATTRACT_NAME { get; set; }
        public decimal ATTRACT_AGE { get; set; }
        public decimal ATTRACT_CAPACITY { get; set; }
        public string PARK_CODE { get; set; }
    
        public virtual themepark themepark { get; set; }
        public virtual ICollection<hour> hours { get; set; }
    }
}
